### PR TITLE
Update action doesn't conserve old data columns.

### PR DESCRIPTION
**Pull request by aldeluis**
Fixed and tested on PostgreSQL.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the PR but this is what `update` is supposed to do (replace an entire existing resource). This is also why the tests are failing. `patch` is used for merging existing data. If you would like the same functionality you can extend the service and call `patch` instead of `update` like this:

```js
knex(...).extend({
  update: function() {
    return this.patch.apply(this, arguments);
  }
});
```

**Comment by aldeluis** [comment]
Right, that's the standard. Then the problem resides in the demo. It's emitting PUT orders instead of PATCH orders:


output_optimized

**Comment by daffl** [comment]
That's a very good point. I totally thought we implemented it so that the whole Todo is sent but if not that's definitely a bug in the example.

**Comment by ekryski** [comment]
Ok I created an issue in the main feathers repo to fix the bug in the demo. I'm going to close this PR since this is actually the expected behaviour of the service. Thanks for pointing this out @aldeluis!

**Pull request closed without merging**
