### PR TITLE
Add createQuery and remove error handler for now

### LINKED ISSUE #87: Exposing the query builder
I'm trying to figure out how to access the query builder object instead of the resolved promise containing row data that's returned by `.find()`.

I'm using this lib vs. my own 'raw' knex connection to map feathers' query operators, and its handling of pagination, etc. At the same time, I often need more granular access to what's returned in a typical `.find` -- left joins, mapping hasMany relationships, scoping SQL to a transaction, etc.

It'd be super handy to have a generic query method that could return the QB instead of the raw results... is there a best practice for doing that?

### PR DESCRIPTION
**Pull request by daffl**
Closes #87

### CODE REVIEW

**Comment by slajax** [comment]
👍

**Comment by ekryski** [comment]
@daffl what was the reasoning for removing the error handler? imho it probably should beefed up rather than pulled out. It catches, transforms and re-throws. Maybe I'm missing something...

**Comment by daffl** [comment]
The reason was that it doesn't seem to do anything. Even when using SQLite none of the errors get converted (and it's not supporting any other DB drivers).

I found it really hard to find all the possible errors the ORMs can throw and map them (I can't find anything about it in the Knex or most of the driver docs). Now that we have error hooks it's pretty easy to just map them to what you need yourself.

**Comment by ekryski** [comment]
Really? The SQLite errors are not getting mapped? Weird. Ya you have to do some digging in the code of the drivers to find the errors that spit out. I'd sort of like to keep it for now if it's not interfering with anything but at the same time if you just ignored me I wouldn't be upset either. 😉 

The only thing is this may be a breaking change if the SQLite errors are getting mapped. I could have sworn they were.

**Comment by daffl** [comment]
Good point. And it doesn't really have anything to do with what this PR is for. I added it back.

**Comment by ekryski** [comment]
:shipit: That is a good point though. We should check to see if this is actually doing stuff and write tests for it and beef it up or just kill it now that we have error hooks.

**Pull request merged**
