### PR TITLE
Add $like query

### PR DESCRIPTION
**Pull request by mcchrish**
Add `$like` operation. A simple alternative to a search query.

### CODE REVIEW

**Comment by daffl** [comment]
Cool. I think this makes sense (as long as Knex sanitizes the query safely). Looks like `knexify` also takes care of removing it from the `where` clause.

**Comment by daffl** [comment]
I'll update this repository to the latest plugin structure (Code coverage, new linter and new Changelog) and then make a release.

**Comment by mcchrish** [comment]
Alright, thanks @daffl 👍

**Comment by daffl** [comment]
Released in v2.4.0. It would be great if you could document this change in https://github.com/feathersjs/feathers-docs/blob/master/databases/knexjs.md

**Comment by mcchrish** [comment]
Hi @daffl, here you go https://github.com/feathersjs/feathers-docs/pull/253. 👍

**Pull request merged**
